// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System.Diagnostics;
using System.CodeDom.Compiler;

#region BBS.Libraries.ConsoleAppTests.Emails.T4Files
namespace BBS.Libraries.ConsoleAppTests.Emails
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Files
	{
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Views
		{
			public static readonly string _root = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/";
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class HandleBars
			{
				public static readonly string _root = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/HandleBars/";
				public static readonly string _01_Mhtml_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/HandleBars/01_Mhtml.cshtml";
				public static readonly string _01_PlainText_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/HandleBars/01_PlainText.cshtml";
				public static readonly string _01_Subject_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/HandleBars/01_Subject.cshtml";
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class Razor
			{
				public static readonly string _root = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Razor/";
				public static readonly string _01_Mhtml_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Razor/01_Mhtml.cshtml";
				public static readonly string _01_PlainText_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Razor/01_PlainText.cshtml";
				public static readonly string _01_Subject_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Razor/01_Subject.cshtml";
			}
			public static readonly string Web_config = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Web.config";
		}
	  public static string RepositryNamespace = "BBS.Libraries.ConsoleAppTests.Emails";
	  
	}
}
#endregion

#region BBS.Libraries.ConsoleAppTests.Emails.T4Links
namespace BBS.Libraries.ConsoleAppTests.Emails
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Links
	{
	}
}
#endregion

